from enum import Enum

class ContextScope(str, Enum):
    CATEGORY = "category"
    MERCHANT = "merchant"
    CUSTOMER = "customer"
    TRIGGER = "trigger"

class SignalType(str, Enum):
    SEARCH_SPIKE = "SEARCH_SPIKE"
    PERFORMANCE_DIP = "PERFORMANCE_DIP"
    PERFORMANCE_IMP = "PERFORMANCE_IMP"
    EXPIRING_OFFER = "EXPIRING_OFFER"
    CUSTOMER_LAPSE = "CUSTOMER_LAPSE"
    FESTIVAL_SEASONAL = "FESTIVAL_SEASONAL"
    RECALL_EVENT = "RECALL_EVENT"
    RESEARCH_INTENT = "RESEARCH_INTENT"

class ConversationState(str, Enum):
    NONE = "NONE"
    OPPORTUNITY_DETECTED = "OPPORTUNITY_DETECTED"
    RECOMMENDATION_SENT = "RECOMMENDATION_SENT"
    MERCHANT_ACCEPTED = "MERCHANT_ACCEPTED"
    ACTION_CONFIRMED = "ACTION_CONFIRMED"
    REJECTED = "REJECTED"
    CLARIFICATION_NEEDED = "CLARIFICATION_NEEDED"
    OFF_TOPIC = "OFF_TOPIC"
    HOSTILE = "HOSTILE"

class TickStatus(str, Enum):
    ACTED = "acted"
    SUPPRESSED = "suppressed"
    NO_ACTION = "no_action"
